INBOX = 'INBOX'
NEXT = 'NEXT'
TODAY = 'TODAY'
PROJECT = 'PROJECT'
CAL = 'CAL'
SOMEDAY = 'SOMEDAY'
DONE = 'DONE'
CANCEL = 'CANCEL'
REMIND = 'REMIND'
FOLDERS = (INBOX, NEXT, TODAY, SOMEDAY, DONE, CANCEL)
PREFIXES = {
    INBOX: '_',
    NEXT: '__',
    TODAY: '___',
    REMIND: 'r',
    SOMEDAY: 's_',
    DONE: 'x',
    CANCEL: 'xx',
}
FOLDER_CHOICES = ((t, t) for t in FOLDERS)
